extends:
  - spectral:oas
  - ./governance-rules/governance-rules.yaml

formats:
  - oas3

functionsDir: ./governance-rules/functions

rules:
  info-contact-required:
    description: "The OpenAPI 'info' object must include a 'contact' field for responsible ownership."
    severity: error
    given: $.info
    then:
      field: contact
      function: truthy

  operation-summary-required:
    description: "Every operation must include a 'summary' field to improve documentation clarity."
    severity: warn
    given: $.paths[*][get, post, put, delete, patch]
    then:
      field: summary
      function: truthy
