extends:
  - "spectral:oas"
  - "./governance-rules/governance-rules.yaml"

rules:
  info-contact:
    description: "The API info object must include a contact field for better support traceability."
    severity: warning
    given: "$.info"
    then:
      field: "contact"
      function: truthy

  operation-summary:
    description: "Each API operation must have a summary to improve documentation."
    severity: warning
    given: "$.paths[*][*]"
    then:
      field: "summary"
      function: truthy

  unused-component:
    description: "Remove unused schemas/components to keep the spec clean."
    severity: info
    given: "$.components.schemas.*"
    then:
      function: unreferenced

  missing-tags:
    description: "Each operation should include a 'tags' field for logical grouping."
    severity: error
    given: "$.paths[*][*]"
    then:
      field: "tags"
      function: truthy

  operation-operationId-naming:
    description: "Enforce camelCase naming convention for operationId."
    severity: error
    given: "$.paths[*][*].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z]+([A-Z][a-z0-9]+)*$"

formats:
  - oas2
  - oas3

functionsDir: "./governance-rules/functions"
