extends:
  - "spectral:oas"
  - "./governance-rules/governance-rules.yaml"

formats:
  - oas3

functionsDir: "./governance-rules/functions"

rules:
  info-contact-required:
    description: "Info object must include a contact field."
    severity: error
    given: "$.info"
    then:
      function: contact-required

  operation-summary-required:
    description: "Each operation must include a summary for documentation clarity."
    severity: warn
    given: "$.paths[*][get,post,put,delete,patch]"
    then:
      field: summary
      function: truthy
