openapi: 3.0.0
info:
  title: Dummy API Spec
  description: This is a sample API specification for testing Spectral linting GitHub Action.
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Say hello
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
